### ISSUE TITLE
The UI of password page changes and shrinks sometimes.

### ISSUE THREAD

**Issue by as-if-iam** [kevalpatel2106/PasscodeView#6]
![nexus5x_7 1 2](https://user-images.githubusercontent.com/20276384/31112478-9873630a-a831-11e7-9b78-e46da113500f.png)

**Activity File**

`import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.Toast;

import com.declaree.declaree.R;
import com.kevalpatel.passcodeview.KeyNamesBuilder;
import com.kevalpatel.passcodeview.PinView;
import com.kevalpatel.passcodeview.indicators.CircleIndicator;
import com.kevalpatel.passcodeview.interfaces.AuthenticationListener;
import com.kevalpatel.passcodeview.keys.RoundKey;

public class PinActivity extends AppCompatActivity {

    private int failureCount = 0;
    private boolean success = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_pin);

        PinView pinView = findViewById(R.id.pin_view);
        pinView.setCorrectPin(new int[]{1, 2, 3, 4});

        pinView.setKeyNames(new KeyNamesBuilder()
                .setKeyOne(this, R.string.key_1)
                .setKeyTwo(this, R.string.key_2)
                .setKeyThree(this, R.string.key_3)
                .setKeyFour(this, R.string.key_4)
                .setKeyFive(this, R.string.key_5)
                .setKeySix(this, R.string.key_6)
                .setKeySeven(this, R.string.key_7)
                .setKeyEight(this, R.string.key_8)
                .setKeyNine(this, R.string.key_9)
                .setKeyZero(this, R.string.key_0));

        pinView.setKey(new RoundKey.Builder(pinView)
                .setKeyPadding(R.dimen.key_padding)
                .setKeyStrokeColorResource(R.color.colorAccent)
                .setKeyStrokeWidth(R.dimen.key_stroke_width)
                .setKeyTextColorResource(R.color.colorPrimaryDark)
                .setKeyTextSize(R.dimen.key_text_size)
                .build());

        pinView.setIndicator(new CircleIndicator.Builder(pinView)
                .setIndicatorRadius(R.dimen.indicator_radius)
                .setIndicatorFilledColorResource(R.color.colorPrimaryDark)
                .setIndicatorStrokeColorResource(R.color.colorAccent)
                .setIndicatorStrokeWidth(R.dimen.indicator_stroke_width)
                .build());

        pinView.setTitle("Use fingerprint or enter PIN to unlock");

        pinView.setAuthenticationListener(new AuthenticationListener() {
            @Override
            public void onAuthenticationSuccessful() {
                //User authenticated successfully.
                //Navigate to next screens.
                Toast.makeText(PinActivity.this, "Success", Toast.LENGTH_SHORT).show();
                success = true;
                onBackPressed();
            }

            @Override
            public void onAuthenticationFailed() {
                //Calls whenever authentication is failed or user is unauthorized.
                //Do something if you want to handle unauthorized user.
                failureCount++;
                success = false;
                if (failureCount > 4)
                    Toast.makeText(PinActivity.this, "You are logged out as entered wrong password", Toast.LENGTH_SHORT).show();
                
            }
        });

    }

    @Override
    public void onBackPressed() {
        if (success)
            super.onBackPressed();
    }
}
`

**UI file code**

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

    <ImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:src="@drawable/logo_dark"
        android:visibility="gone"
        android:contentDescription="@string/app_name"/>

    <com.kevalpatel.passcodeview.PinView
        android:id="@+id/pin_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/imageView"
        app:dividerColor="@color/colorPrimaryDark"
        app:fingerprintDefaultText="Scan your finger to unlock application"
        app:fingerprintEnable="true"
        app:fingerprintTextColor="@color/colorPrimaryDark"
        app:fingerprintTextSize="@dimen/finger_print_text_size"
        app:titleTextColor="@android:color/white"/>

</RelativeLayout>
`

**Comment by asif84468** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

    <ImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:src="@drawable/logo_dark"
        android:visibility="gone"
        android:contentDescription="@string/app_name"/>

    <com.kevalpatel.passcodeview.PinView
        android:id="@+id/pin_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/imageView"
        app:dividerColor="@color/colorPrimaryDark"
        app:fingerprintDefaultText="Scan your finger to unlock application"
        app:fingerprintEnable="true"
        app:fingerprintTextColor="@color/colorPrimaryDark"
        app:fingerprintTextSize="@dimen/finger_print_text_size"
        app:titleTextColor="@android:color/white"/>

</RelativeLayout>

**Comment by AkshayPathak** [comment]
Same issue, can we get an update on this @kevalpatel2106?

**Comment by fritz-playmaker** [comment]
Same issue here @kevalpatel2106 . Kindly update. Thank you

**Comment by kpamansoor** [comment]
I'm also facing same issue, can we get it updated?

**Comment by kevalpatel2106** [comment]
@kpamansoor @asif84468 @AkshayPathak @fritz-playmaker I tried this with diffrent phones and I am able to regenerate this issue. But, I am not able to reproduce this issue with specific steps and also not able to find the cause of this issue. Does any of you have any suggestions or ideas?

**Comment by kevalpatel2106** [comment]
Fixed in #8 . Fix will be available in next release.

**Comment by kpamansoor** [comment]
I removed the plugin and installed, still getting same issue. Haven't you update the version after meging this or i'm doing in wrong way?

**Comment by kevalpatel2106** [comment]
@kpamansoor I mearged the PR into the master branch. I will release the update version soon.

**Comment by kevalpatel2106** [comment]
Version 1.2.1 released with the fix.
